	
service: sls-flask-iris

plugins:
  - serverless-python-requirements
  - serverless-wsgi

# configs for plugins
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    zip: true

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-1
  deploymentBucket: python-serverless-deployment-s3

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: 
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{proxy+}